# Generated by Django 2.2.19 on 2023-02-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230214_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='slug'),
        ),
    ]
